### ISSUE TITLE
Bugfix SpecifiedInput usage

### ISSUE THREAD

**Issue by afiffon** [mjb3279/rust-kbkdf#1]
Hello, I have issued a fix to the SpecifiedInput in your gitlab repo: https://gitlab.com/michael.j.boquard/rust-kbkdf/-/merge_requests/1
Please check out the changes -- the injected 0 between label and context was '0'=48, and the encoded length L was wrong. This is only relevant in SpecifiedInput.

**Comment by afiffon** [comment]
Hi @mike-boquard, I'd like to have your help regarding the issued fix -- is there any chance you'd be able to create a new release of the crate, after it's fixed?
+ I also saw that another MR was issued, regarding a somewhat-similar bug fix: https://gitlab.com/michael.j.boquard/rust-kbkdf/-/merge_requests/2.
Would really appreciate your help!

**Comment by mike-boquard** [comment]
@AvivNaaman I just published v1.1.1 with both fixes

**Comment by afiffon** [comment]
Thanks so much!

Your project is crucial for my smb-rs crate: https://github.com/AvivNaaman/smb-rs
